# Generated by Django 3.0.5 on 2020-04-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsinfo',
            name='newsheading',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
