# Generated by Django 3.0.5 on 2020-04-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0002_newsinfo_newsheading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsinfo',
            name='newscategory',
            field=models.CharField(max_length=15),
        ),
    ]
