# Generated by Django 3.0.5 on 2020-04-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0004_adv_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='advside',
            field=models.CharField(default='left', max_length=10),
        ),
    ]
