# Generated by Django 3.0.6 on 2020-06-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0006_auto_20200529_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(default=' ', max_length=200)),
                ('lastname', models.CharField(default=' ', max_length=200)),
                ('city', models.CharField(default=' ', max_length=200)),
                ('dob', models.DateTimeField()),
                ('status', models.CharField(default='Pending', max_length=200)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
