# Generated by Django 3.0.6 on 2020-06-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0007_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
    ]
