# Generated by Django 3.0.6 on 2020-06-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0008_application_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
