# Generated by Django 3.0.6 on 2020-06-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0009_application_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dob',
            field=models.DateField(),
        ),
    ]
