# Generated by Django 3.0.6 on 2020-06-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0010_auto_20200606_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='application',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In-Review', 'In-Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Waiting-Info', 'Waiting-Info')], default='Pending', max_length=200),
        ),
    ]
