# Generated by Django 3.0.6 on 2020-06-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0011_auto_20200609_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='file1',
            field=models.FileField(blank=True, default='images/dummy.pdf', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='file2',
            field=models.FileField(blank=True, default='images/dummy.pdf', null=True, upload_to='images/'),
        ),
    ]
