# Generated by Django 3.0.6 on 2020-06-11 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0012_auto_20200611_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='application',
            name='file2',
        ),
    ]
