# Generated by Django 3.0.6 on 2020-06-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0013_auto_20200611_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='file1',
            field=models.FileField(default='images/dummy.pdf', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='application',
            name='file2',
            field=models.FileField(default='images/dummy.pdf', upload_to='images/'),
        ),
    ]
