# Generated by Django 3.0.6 on 2020-06-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0014_auto_20200611_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='university',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('India', 'India'), ('UK', 'UK'), ('USA', 'USA')], default='UK', max_length=20)),
                ('uniname', models.CharField(max_length=100)),
                ('loc', models.CharField(max_length=200)),
            ],
        ),
    ]
