# Generated by Django 3.0.6 on 2020-06-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0017_auto_20200622_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(default=' ', max_length=2000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
