# Generated by Django 3.0.6 on 2020-06-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0018_auto_20200622_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='cname',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(default='None', max_length=2000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
