# Generated by Django 3.0.6 on 2020-06-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0019_auto_20200622_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cname',
            field=models.CharField(default='customer', max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(default='customer', max_length=2000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='customer@gmail.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='customer', max_length=100),
        ),
    ]
