# Generated by Django 3.0.6 on 2020-06-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0020_auto_20200622_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='customer@gmail.com', max_length=50),
        ),
    ]
