# Generated by Django 3.0.6 on 2020-06-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0022_auto_20200622_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cname',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(default='None', max_length=2000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
