# Generated by Django 3.0.6 on 2020-06-23 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0024_auto_20200623_0711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='cname',
            new_name='name',
        ),
    ]
